"""Merge a participant's real scan-built font with FontDiffuser-generated glyphs.

real  : e.g. build/0005MissHo.ttf -- copied verbatim, never re-traced, so the
        hand-written part of the output is byte-identical.
generated: e.g. kaggle/gen3500/results-v1/outputs/glyphs/*.png, 96px, traced through
        the SAME potrace path build_font.py uses (2026-09-21 experiment: raw 96
        beats any upscale -- gaussian merges neighbouring strokes).
Only correction applied: generated glyphs run larger than the real ink height, so
they're scaled vertically about the em centre by --yscale. This ratio is per-person
(measured 1.082x for MissHo 2026-09-20 -> 0.925; measured 1.051x for Phoon
2026-09-26 -> 0.951) -- measure fresh for each new participant, don't assume the
previous person's constant carries over. Stroke width needs no fix for either so
far -- measured ~1.02x at threshold 128, bbox ink density ~1.0x.
"""
import argparse
import glob
import os
import sys

import numpy as np
from PIL import Image
from fontTools.ttLib import TTFont
from fontTools.pens.ttGlyphPen import TTGlyphPen

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_font as bf

THRESH = 128             # matches measured stroke width; see module docstring
EM_MID = bf.ASCENT - bf.UPM / 2.0


def trace_generated(png, yscale, thresh=THRESH):
    """96px generated cell -> TrueType glyph, squashed to her ink height."""
    bmp = (np.asarray(Image.open(png).convert("L")) < thresh).astype(np.uint8)
    if bmp.sum() == 0:
        return None
    glyph = bf.trace_to_glyph(bmp, reverse=False)
    if glyph is None:
        return None
    if yscale != 1.0:
        c = glyph.coordinates
        for i in range(len(c)):
            x, y = c[i]
            c[i] = (x, int(round(EM_MID + (y - EM_MID) * yscale)))
    return glyph


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--real", default="D:/handwriting-font/build/0005MissHo.ttf")
    ap.add_argument("--gen", default="D:/handwriting-font/kaggle/gen3500/results-v1/outputs/glyphs")
    ap.add_argument("--out", default="D:/handwriting-font/build/0005MissHo-full.ttf")
    ap.add_argument("--family", default="0005MissHo Hand Full")
    ap.add_argument("--yscale", type=float, required=True,
                     help="generated/real ink-height ratio, inverted -- measure per person, see module docstring")
    a = ap.parse_args()
    assert not os.path.exists(a.out) or os.environ.get("ALLOW_OVERWRITE"), (
        a.out + " exists; set ALLOW_OVERWRITE=1 to replace it")

    font = TTFont(a.real)
    glyf, hmtx = font["glyf"], font["hmtx"]
    cmap_before = dict(font.getBestCmap())
    order = list(font.getGlyphOrder())
    real_names = set(order)

    pngs = sorted(glob.glob(os.path.join(a.gen, "*.png")))
    assert pngs, "no generated glyphs at " + a.gen
    added, skipped_dup, failed = [], [], []
    for p in pngs:
        cp = int(os.path.basename(p)[1:5], 16)
        if cp in cmap_before:                    # her own hand always wins
            skipped_dup.append(cp)
            continue
        name = "uni%04X" % cp
        assert name not in real_names, name
        g = trace_generated(p, a.yscale)
        if g is None:
            failed.append(cp)
            continue
        glyf[name] = g
        hmtx[name] = (bf.UPM, 0)
        order.append(name)
        added.append(cp)

    font.setGlyphOrder(order)
    font["maxp"].numGlyphs = len(order)
    for table in font["cmap"].tables:
        for cp in added:
            table.cmap[cp] = "uni%04X" % cp

    n = font["name"]
    note = ("%d glyphs traced from this participant's handwriting; %d generated by a "
            "FontDiffuser model fine-tuned on their hand (AI-completed, not hand-written)."
            % (len(cmap_before), len(added)))
    for nid, val in ((1, a.family), (4, a.family + " Regular"),
                     (6, a.family.replace(" ", "") + "-Regular"), (10, note)):
        n.setName(val, nid, 3, 1, 0x409)
        n.setName(val, nid, 1, 0, 0)
    font.save(a.out)

    # read back: the file on disk is what gets checked, not the in-memory object
    rb = TTFont(a.out)
    rb_cmap = rb.getBestCmap()
    lv1 = [c for c in open("D:/handwriting-font/chars-3500-level1.txt", encoding="utf-8").read()
           if 0x4E00 <= ord(c) <= 0x9FFF]
    missing = [c for c in lv1 if ord(c) not in rb_cmap]
    empty = [c for c in lv1 if ord(c) in rb_cmap
             and not rb["glyf"][rb_cmap[ord(c)]].numberOfContours]
    print("real %d + generated %d = %d cmap entries (read back %d)"
          % (len(cmap_before), len(added), len(cmap_before) + len(added), len(rb_cmap)))
    print("generated skipped as duplicate of her hand: %d | trace failures: %d %s"
          % (len(skipped_dup), len(failed), "".join(chr(c) for c in failed)))
    print("level-1 3500 coverage: missing %d, empty-outline %d" % (len(missing), len(empty)))
    assert not missing and not empty, (missing[:10], empty[:10])
    print("wrote", a.out, os.path.getsize(a.out) // 1024, "KB")


if __name__ == "__main__":
    main()
