"""Proof sheet for a participant's -full.ttf: real sentences, AI-completed chars tinted.

Grey cell = glyph generated by the fine-tuned model. White = they wrote it.
"""
import argparse
import os
import sys

from PIL import Image, ImageDraw, ImageFont
from fontTools.ttLib import TTFont

LINES = [
    "南华独中九十周年校庆",
    "遗字千金手写字体计划",
    "这一行字里有些是本人亲手写的",
    "其余由模型补齐印刷排版可用",
    "春风化雨桃李满门薪火相传",
    "教育的意义在于点燃而非灌输",
]
SIZE, PAD, GAP = 72, 28, 22


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--full", required=True)
    ap.add_argument("--real", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    real_cmap = set(TTFont(a.real).getBestCmap())
    f = ImageFont.truetype(a.full, SIZE)
    lab = ImageFont.truetype("C:/Windows/Fonts/msyh.ttc", 18)
    cols = max(len(l) for l in LINES)
    W = PAD * 2 + cols * SIZE
    H = PAD * 2 + 30 + len(LINES) * (SIZE + GAP)
    img = Image.new("RGB", (W, H), "white")
    dr = ImageDraw.Draw(img)
    dr.text((PAD, 6), "灰底＝模型补的字（本人没写过）｜白底＝本人亲手写的", font=lab, fill=(90, 90, 90))
    gen = 0
    for i, line in enumerate(LINES):
        y = PAD + 30 + i * (SIZE + GAP)
        for j, ch in enumerate(line):
            x = PAD + j * SIZE
            if ord(ch) not in real_cmap:
                dr.rectangle([x, y, x + SIZE - 2, y + SIZE - 2], fill=(232, 232, 232))
                gen += 1
            dr.text((x, y), ch, font=f, fill=0)
    img.save(a.out)
    total = sum(len(l) for l in LINES)
    print("proof", img.size, "->", a.out)
    print("chars %d, of which AI-completed %d (%.0f%%)" % (total, gen, 100.0 * gen / total))


if __name__ == "__main__":
    main()
